# Generated by Django 2.2.5 on 2019-10-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_id_in_service',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
